version: '3.8'

services:
  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=material-applications-redis-1

  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000

  redis:
    image: redis:7.0.11

