version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgresdb
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    build: ./example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
      - REQUEST_ORIGIN=http://localhost
    depends_on:
      - db
  frontend:
    build: ./example-frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:80/api/
    depends_on:
      - db
      - backend
  proxy:
    image: nginx:1.25.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  redis:
    image: redis:7.0.11-alpine

volumes:
  database:
