name: Push to DockerHub

on:
  push:
    branches:
      - main
      
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change Directory
      run: |
        cd Part\ 3/exercise3-1/express-app/
    - name: DockerHub Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: wallysf/express-app:latest
